### ISSUE TITLE
Publish documentation on Github Pages

### ISSUE THREAD

**Issue by jy95** [weiran-zsd/dts-cli#54]
First let me thank you for your amazing work on this fork.
For documentation reasons, it would be nice to have the [tsdx website](https://github.com/weiran-zsd/dts-cli/tree/main/website) available on https://weiran.github.io/dts-cli/ .

Thanks in advance

**Comment by aladdin-add** [comment]
thanks for bring this up!

tsdx website was deployed by vercel, but no longer working in the fork for some reasons. gh pages sounds a desirable alternative! 👍

**Comment by aladdin-add** [comment]
cc @sidwebworks

**Comment by sidwebworks** [comment]
@jy95 Sounds good, I will start a branch for this. I do think it's possible to publish the Next js site on Github pages.

**Comment by jy95** [comment]
@sidwebworks I used [peaceiris/actions-gh-pages@v3](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next) on others projects (like this [one](https://github.com/jy95/i18n-tools/blob/master/.github/workflows/documentation.yml) that relies on Docusaurus) and it often works fine.

**Comment by jy95** [comment]
For the present time, It is better to keep what we already have. ( The simpler, the better ^^)

**Comment by sidwebworks** [comment]
Everything is working now, Although i am thinking to deploy this on vercel, should I do it then ? @aladdin-add

**Comment by sidwebworks** [comment]
Oops, Looks like vercel giving some build errors. Will have to check this.
```
14:15:30.495  	Retrieving list of deployment files...
14:15:32.039  	Downloading 44 deployment files...
14:15:33.657  	Analyzing source code...
14:15:35.208  	Installing build runtime...
14:15:38.387  	Build runtime installed: 3.178s
14:15:41.632  	Looking up build cache...
14:15:41.902  	Build Cache not found
14:15:43.245  	Installing dependencies...
14:15:43.555  	yarn install v1.22.11
14:15:43.652  	[1/4] Resolving packages...
14:15:50.099  	warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
14:15:50.100  	warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
14:15:51.372  	warning next-google-fonts@1.3.0: As of Next.js 10.2, Google Fonts are automatically optimized! For more info, see https://github.com/joe-bell/next-google-fonts
14:15:57.909  	warning postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
14:16:01.015  	[2/4] Fetching packages...
14:16:13.458  	info @next/swc-darwin-arm64@11.1.2: The platform "linux" is incompatible with this module.
14:16:13.459  	info "@next/swc-darwin-arm64@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
14:16:13.459  	info @next/swc-darwin-arm64@11.1.2: The CPU architecture "x64" is incompatible with this module.
14:16:13.459  	info @next/swc-darwin-x64@11.1.2: The platform "linux" is incompatible with this module.
14:16:13.459  	info "@next/swc-darwin-x64@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
14:16:13.460  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
14:16:13.460  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
14:16:13.462  	info @next/swc-win32-x64-msvc@11.1.2: The platform "linux" is incompatible with this module.
14:16:13.462  	info "@next/swc-win32-x64-msvc@11.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
14:16:13.466  	[3/4] Linking dependencies...
14:16:13.468  	warning " > @reach/skip-nav@0.10.5" has incorrect peer dependency "react@^16.8.0".
14:16:13.469  	warning " > @reach/skip-nav@0.10.5" has incorrect peer dependency "react-dom@^16.8.0".
14:16:13.469  	warning "@reach/skip-nav > @reach/utils@0.10.5" has incorrect peer dependency "react@^16.8.0".
14:16:13.471  	warning "@reach/skip-nav > @reach/utils@0.10.5" has incorrect peer dependency "react-dom@^16.8.0".
14:16:13.472  	warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
14:16:17.679  	[4/4] Building fresh packages...
14:16:17.728  	success Saved lockfile.
14:16:17.733  	Done in 34.18s.
14:16:17.758  	Detected Next.js version: 11.1.2
14:16:17.760  	Running "yarn run build"
14:16:18.102  	yarn run v1.22.11
14:16:18.136  	$ next build
14:16:19.143  	info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
14:16:19.320  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
14:16:19.321  	This information is used to shape Next.js' roadmap and prioritize features.
14:16:19.321  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
14:16:19.321  	https://nextjs.org/telemetry
14:16:19.390  	info  - Checking validity of types...
14:16:19.563  	warn  - No ESLint configuration detected. Run next lint to begin setup
14:16:19.567  	info  - Creating an optimized production build...
14:16:20.394  	info  - Using external babel configuration from /vercel/path0/.babelrc
14:16:27.445  	warn - You have enabled the JIT engine which is currently in preview.
14:16:27.445  	warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
14:16:40.592  	info  - Compiled successfully
14:16:40.593  	info  - Collecting page data...
14:16:41.141  	info  - Generating static pages (0/7)
14:16:41.691  	Error occurred prerendering page "/customization". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.691  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.692  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.692  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.692  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.693  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.693  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.693  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.694  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.694  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.694  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.695  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.695  	info  - Generating static pages (1/7)
14:16:41.697  	Error occurred prerendering page "/api-reference". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.698  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.698  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.699  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.699  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.699  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.700  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.700  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.703  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.703  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.704  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.704  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.720  	Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.721  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.721  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.722  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.722  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.723  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.723  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.723  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.724  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.724  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.725  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.725  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.727  	Error occurred prerendering page "/optimization". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.730  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.731  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.731  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.731  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.731  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.732  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.732  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.732  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.732  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.733  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.733  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.733  	Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.733  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.733  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.734  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.734  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.734  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.734  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.734  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.734  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.734  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.735  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.735  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.735  	info  - Generating static pages (3/7)
14:16:41.735  	info  - Generating static pages (5/7)
14:16:41.737  	Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.737  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.737  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.737  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.738  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.738  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.738  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.738  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.738  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.738  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.738  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.738  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.898  	Error occurred prerendering page "/change-log". Read more: https://nextjs.org/docs/messages/prerender-error
14:16:41.898  	Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
14:16:41.898  	    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:32)
14:16:41.898  	    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:16:41.898  	    at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
14:16:41.898  	    at Object.renderPage (/vercel/path0/node_modules/next/dist/server/render.js:596:45)
14:16:41.898  	    at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:603:19)
14:16:41.899  	    at Object.loadGetInitialProps (/vercel/path0/node_modules/next/dist/shared/lib/utils.js:69:29)
14:16:41.899  	    at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:609:48)
14:16:41.899  	    at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:647:34)
14:16:41.899  	    at processTicksAndRejections (internal/process/task_queues.js:95:5)
14:16:41.899  	    at async /vercel/path0/node_modules/next/dist/export/worker.js:273:36
14:16:41.899  	> Build error occurred
14:16:41.899  	info  - Generating static pages (7/7)
14:16:41.901  	Error: Export encountered errors on following paths:
14:16:41.901  		/
14:16:41.901  		/404
14:16:41.902  		/500
14:16:41.902  		/api-reference
14:16:41.903  		/change-log
14:16:41.903  		/customization
14:16:41.903  		/optimization
14:16:41.903  	    at /vercel/path0/node_modules/next/dist/export/index.js:487:19
14:16:41.903  	    at runMicrotasks (<anonymous>)
14:16:41.903  	    at processTicksAndRejections (internal/process/task_queues.js:95:5)
14:16:41.904  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.904  	    at async /vercel/path0/node_modules/next/dist/build/index.js:833:17
14:16:41.904  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.904  	    at async /vercel/path0/node_modules/next/dist/build/index.js:707:13
14:16:41.904  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
14:16:41.904  	    at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
14:16:41.940  	error Command failed with exit code 1.
14:16:41.941  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:16:41.961  	Error: Command "yarn run build" exited with 1
```

**Comment by aladdin-add** [comment]
vercel was a paid service for teams. so, let's just deploy to gh pages. :)

**Comment by aladdin-add** [comment]
just add u as admin. :)

**Comment by sidwebworks** [comment]
Alright thanks buddy, I will then upload it to github pages now. :)

**Comment by aladdin-add** [comment]
👍 looks great!
